import test from "node:test";
import assert from "node:assert/strict";
import {initialState,transition,assertInvariants,hash,fixture,view,available,LEASE_MS} from "../lib/relay/engine.mjs";
import {execute,getView} from "../lib/relay/service.mjs";
import {DatabaseSync} from "node:sqlite";
const start=1700000000000;
const model={name:"test-model",digest:"a".repeat(64),runtime:"b".repeat(64),template:"c".repeat(64),context:8192,minVram:4096};
const doc={title:"한글 😀",text:"라이선스: MIT\n지원 GPU: CUDA",url:"https://example.org/spec"};
const request=(docs=[doc],extra={})=>({title:"test",fields:["라이선스"],documents:docs,budget:100,minutes:30,publicData:true,modelId:"fixture-v1",...extra});
async function demo(docs=[doc],extra={}){const s=initialState(start);await transition(s,"demo","create",request(docs,extra),start);return s}
async function setup(){const s=initialState(start);const m=await transition(s,"live","model",model,start);const token=crypto.randomUUID()+crypto.randomUUID();const n=await transition(s,"live","node",{name:"GPU-A",modelId:m.modelId,vram:8192,tokenHash:await hash(token)},start);await transition(s,"live","create",request([doc],{modelId:m.modelId}),start);const out=await transition(s,"live","poll",{modelDigest:model.digest,runtime:model.runtime,template:model.template},start,n.nodeId);const task=out.task;const payload={taskId:task.taskId,attemptId:task.lease.attemptId,epoch:task.lease.epoch,modelDigest:model.digest,runtime:model.runtime,template:model.template,raw:fixture(doc,["라이선스"]),finishReason:"stop",usage:{prompt_tokens:100,completion_tokens:30}};return {s,m,n,token,task,payload}}
const allTasks=s=>s.books.demo.jobs.flatMap(j=>j.tasks);
test("reservation is durable, isolated by execution mode and released on completion",async()=>{const s=await demo();assert.equal(available(s.books.demo),990);assert.equal(available(s.books.live),1000);await transition(s,"demo","tick",{},start);await transition(s,"demo","tick",{},start+7000);assert.equal(s.books.demo.jobs[0].status,"completed");assert.equal(s.books.demo.accounts.requester,990);assertInvariants(s)});
test("owner pause preserves completed maps and reassigns only unfinished task",async()=>{const s=await demo([doc,doc,doc,doc]);await transition(s,"demo","tick",{},start);const t=allTasks(s).find(t=>t.lease.nodeId==="demo-0");await transition(s,"demo","pause",{nodeId:"demo-0"},start+1000);await transition(s,"demo","tick",{},start+7000);assert.equal(allTasks(s).filter(t=>t.status==="settled").length,2);await transition(s,"demo","tick",{},start+14000);assert.equal(s.books.demo.jobs[0].status,"completed");assert.equal(t.attempts.length,2);assert.equal(s.books.demo.ledger.filter(l=>l.type==="settlement").length,4);assertInvariants(s)});
test("duplicate submission returns original receipt without a second payment",async()=>{const {s,n,payload}=await setup();const a=await transition(s,"live","submit",payload,start+1000,n.nodeId);const b=await transition(s,"live","submit",payload,start+2000,n.nodeId);assert.equal(a.receipt,b.receipt);assert.equal(b.duplicate,true);assert.equal(s.books.live.accounts.requester,990);assertInvariants(s)});
test("archive preserves receipt identity but removes content",async()=>{const {s,n,payload}=await setup();const a=await transition(s,"live","submit",payload,start+1000,n.nodeId);await transition(s,"live","archive",{jobId:s.books.live.jobs[0].id},start+2000);const b=await transition(s,"live","submit",payload,start+3000,n.nodeId);assert.equal(a.receipt,b.receipt);assert.equal(s.books.live.jobs[0].documents[0].text,undefined);await assert.rejects(transition(s,"live","submit",{...payload,raw:"different"},start+3000,n.nodeId),e=>e.status===409)});
test("old lease cannot revive itself or claim a new task through heartbeat",async()=>{const {s,n,payload}=await setup();await assert.rejects(transition(s,"live","poll",{...model,modelDigest:model.digest,attemptId:payload.attemptId,epoch:payload.epoch},start+LEASE_MS+1,n.nodeId),e=>e.status===409);assert.equal(s.books.live.jobs[0].tasks[0].attempts.length,1);await assert.rejects(transition(s,"live","submit",payload,start+LEASE_MS+1,n.nodeId),e=>e.status===409)});
test("late result from A cannot affect reassigned result from B",async()=>{const {s,m,n,payload}=await setup();const other=await transition(s,"live","node",{name:"B",modelId:m.modelId,vram:8192,tokenHash:"d".repeat(64)},start);const poll=await transition(s,"live","poll",{modelDigest:model.digest,runtime:model.runtime,template:model.template},start+LEASE_MS+1,other.nodeId);await assert.rejects(transition(s,"live","submit",payload,start+LEASE_MS+2,n.nodeId),e=>e.status===409);await transition(s,"live","submit",{...payload,attemptId:poll.task.lease.attemptId,epoch:poll.task.lease.epoch},start+LEASE_MS+3,other.nodeId);assert.equal(s.books.live.accounts.requester,990);assertInvariants(s)});
test("cancel releases reservation, invalidates granted results",async()=>{const {s,n,payload}=await setup();await transition(s,"live","cancel",{jobId:s.books.live.jobs[0].id},start+100);assert.equal(available(s.books.live),1000);await assert.rejects(transition(s,"live","submit",payload,start+200,n.nodeId),e=>e.status===409);assertInvariants(s)});
test("quality rejection does not silently deny a completed execution payment",async()=>{const {s,n,payload}=await setup();await transition(s,"live","submit",{...payload,raw:JSON.stringify({items:[{field:"라이선스",value:"GPL",quote:"not in document"}]})},start+1,n.nodeId);assert.equal(s.books.live.jobs[0].status,"partial");assert.equal(s.books.live.jobs[0].tasks[0].quality,"failed");assert.equal(s.books.live.accounts.requester,990);assertInvariants(s)});
test("quality retry makes a new logical task within the original budget",async()=>{const {s,n,payload}=await setup();await transition(s,"live","submit",{...payload,raw:"invalid json"},start+1,n.nodeId);const j=s.books.live.jobs[0];await transition(s,"live","retry",{jobId:j.id,documentId:j.documents[0].id},start+2);assert.equal(j.spent,10);assert.equal(j.reserved,10);assert.equal(j.tasks.length,2);assert.notEqual(j.documents[0].taskId,payload.taskId);assertInvariants(s)});
test("retry cannot exceed budget",async()=>{const {s,n,payload}=await setup();const j=s.books.live.jobs[0];j.budget=10;await transition(s,"live","submit",{...payload,raw:"bad"},start+1,n.nodeId);await assert.rejects(transition(s,"live","retry",{jobId:j.id,documentId:j.documents[0].id},start+2),e=>e.status===409)});
test("mismatched model contract fails closed",async()=>{const {s,n,payload}=await setup();await assert.rejects(transition(s,"live","submit",{...payload,modelDigest:"wrong"},start+1,n.nodeId),e=>e.status===409);assert.equal(s.books.live.accounts.requester,1000)});
test("other provider cannot submit another node's result",async()=>{const {s,m,payload}=await setup();const other=await transition(s,"live","node",{name:"B",modelId:m.modelId,vram:8192,tokenHash:"d".repeat(64)},start);await assert.rejects(transition(s,"live","submit",payload,start+1,other.nodeId),e=>e.status===409)});
test("revoked provider loses result and polling rights",async()=>{const {s,n,payload}=await setup();await transition(s,"live","revoke",{nodeId:n.nodeId},start+1);await assert.rejects(transition(s,"live","submit",payload,start+2,n.nodeId),e=>e.status===403)});
test("supply allowlist prevents assignment to a faster disallowed node",async()=>{const s=await demo([doc],{allowedNodes:["demo-2"]});await transition(s,"demo","tick",{},start);assert.equal(allTasks(s)[0].lease.nodeId,"demo-2");assertInvariants(s)});
test("node owns no more than one active slot",async()=>{const {s,n}=await setup();const p={modelDigest:model.digest,runtime:model.runtime,template:model.template};const a=await transition(s,"live","poll",p,start+10,n.nodeId);const b=await transition(s,"live","poll",p,start+11,n.nodeId);assert.equal(a.task.lease.attemptId,b.task.lease.attemptId);assertInvariants(s)});
test("deadline terminalizes unfinished tasks and refunds reserved capacity",async()=>{const s=await demo([doc],{minutes:1});await transition(s,"demo","tick",{},start+60001);assert.equal(s.books.demo.jobs[0].status,"partial");assert.equal(available(s.books.demo),1000);assertInvariants(s)});
test("technical retry cap is finite",async()=>{const s=await demo();for(let i=0;i<4;i++)await transition(s,"demo","tick",{},start+i*(LEASE_MS+1));assert.equal(allTasks(s)[0].attempts.length,3);assert.equal(allTasks(s)[0].status,"failed");assert.equal(available(s.books.demo),1000)});
test("Unicode source position uses documented UTF-16 offsets",async()=>{const {s,n,payload}=await setup();const d=s.books.live.jobs[0].documents[0];d.text="😀 한글\n라이선스: MIT";await transition(s,"live","submit",payload,start+1,n.nodeId);const item=s.books.live.jobs[0].tasks[0].items[0];assert.equal(item.start,6);assert.equal(d.text.slice(item.start,item.end),item.quote)});
test("usage is whitelisted and never prices settlement",async()=>{const {s,n,payload}=await setup();await transition(s,"live","submit",{...payload,usage:{prompt_tokens:9,completion_tokens:999999,arbitrary:"x".repeat(60000)}},start+1,n.nodeId);const t=s.books.live.jobs[0].tasks[0];assert.equal(t.usage.arbitrary,undefined);assert.equal(s.books.live.jobs[0].spent,10)});
test("source URLs reject active schemes and demo/live wallets never transfer",async()=>{const s=initialState(start);await assert.rejects(transition(s,"demo","create",request([{...doc,url:"javascript:alert(1)"}]),start));assert.equal(s.books.live.accounts.requester,1000);assert.equal(view(s).books.demo.nodes[0].tokenHash,undefined)});
class MemoryStore{
 constructor(state){this.row=state?{revision:0,state:JSON.stringify(state)}:null;this.conflicts=0;}
 async read(){await Promise.resolve();return this.row?{...this.row}:null}
 async insert(id,state){if(!this.row)this.row={revision:0,state}}
 async compareAndSwap(id,revision,state){await Promise.resolve();if(this.row.revision!==revision){this.conflicts++;return false;}this.row={revision:revision+1,state};return true;}
}
test("concurrent workflow reservations cannot overspend one balance",async()=>{const s=initialState(start);s.books.demo.accounts.requester=10;s.books.demo.issued=10;s.books.demo.ledger[0].amount=10;const store=new MemoryStore(s);const calls=[0,1].map(()=>execute(store,"test",{mode:"demo",action:"create",payload:request(),requestId:crypto.randomUUID()},{now:start}));const result=await Promise.allSettled(calls);assert.equal(result.filter(r=>r.status==="fulfilled").length,1);assert.equal(store.conflicts,1);assertInvariants(JSON.parse(store.row.state))});
test("concurrent duplicate submissions settle once via CAS",async()=>{const {s,n,token,payload}=await setup();const store=new MemoryStore(s);const command={mode:"live",action:"submit",payload,nodeId:n.nodeId,token};const result=await Promise.all([execute(store,"test",command,{provider:true,now:start+1}),execute(store,"test",command,{provider:true,now:start+1})]);assert.equal(result[0].result.receipt,result[1].result.receipt);assertInvariants(JSON.parse(store.row.state));assert.equal(JSON.parse(store.row.state).books.live.ledger.length,2)});
test("idempotent creation and payload mismatch checks",async()=>{const store=new MemoryStore();const command={mode:"demo",action:"create",payload:request(),requestId:crypto.randomUUID()};const a=await execute(store,"test",command,{now:start});const b=await execute(store,"test",command,{now:start});assert.equal(a.result.jobId,b.result.jobId);await assert.rejects(execute(store,"test",{...command,payload:{...command.payload,title:"changed"}},{now:start}),e=>e.status===409)});
test("client retained key survives a lost node-creation response",async()=>{const {s,m}=await setup();const store=new MemoryStore(s);const token=crypto.randomUUID()+crypto.randomUUID();const command={mode:"live",action:"node",payload:{name:"B",modelId:m.modelId,vram:8192,token},requestId:crypto.randomUUID()};const a=await execute(store,"test",command,{now:start});const b=await execute(store,"test",command,{now:start});assert.equal(a.result.nodeId,b.result.nodeId);assert.equal(JSON.parse(store.row.state).books.live.nodes.at(-1).tokenHash,await hash(token));assert.ok(!store.row.state.includes(token))});
test("CAS retries refresh the server clock",async()=>{const {s,n,token,payload}=await setup();const store=new MemoryStore(s);const original=store.compareAndSwap.bind(store);let attempts=0,now=start+10;store.compareAndSwap=async(...args)=>{if(!attempts++){now+=1000;return false;}return original(...args)};await execute(store,"test",{mode:"live",action:"poll",nodeId:n.nodeId,token,payload:{...model,modelDigest:model.digest,attemptId:payload.attemptId,epoch:payload.epoch}},{provider:true,clock:()=>now});assert.equal(JSON.parse(store.row.state).books.live.nodes[0].lastSeen,start+1010)});
test("maximum escaped result fits reserved size capacity",async()=>{const {s,n,payload}=await setup();const j=s.books.live.jobs[0];j.fields=["a","b","c","d","e","f"];j.documents[0].text='"'.repeat(475);payload.raw=JSON.stringify({items:j.fields.map(field=>({field,value:'"'.repeat(475),quote:'"'.repeat(475)}))});const before=Buffer.byteLength(JSON.stringify(s));await transition(s,"live","submit",payload,start+1,n.nodeId);const growth=Buffer.byteLength(JSON.stringify(s))-before;assert.ok(growth<64000);assert.equal(j.status,"completed");assertInvariants(s)});
test("SQLite persistence recovers state after closing and reopening database",async(t)=>{const fs=await import("node:fs/promises");await fs.mkdir("work",{recursive:true});const path="work/test-restart-"+crypto.randomUUID()+".sqlite";let db=new DatabaseSync(path);db.exec("CREATE TABLE relay_pools(id TEXT PRIMARY KEY,revision INTEGER,state TEXT)");const store={read:async id=>db.prepare("SELECT * FROM relay_pools WHERE id=?").get(id),insert:async(id,state)=>db.prepare("INSERT OR IGNORE INTO relay_pools VALUES (?,0,?)").run(id,state),compareAndSwap:async(id,rev,state)=>db.prepare("UPDATE relay_pools SET state=?,revision=revision+1 WHERE id=? AND revision=?").run(state,id,rev).changes===1};const a=await execute(store,"test",{mode:"demo",action:"create",payload:request(),requestId:crypto.randomUUID()},{now:start});db.close();db=new DatabaseSync(path);const b=await getView(store,"test");assert.equal(b.state.books.demo.jobs[0].id,a.result.jobId);assert.equal(b.state.books.demo.reserved,10);db.close();await fs.unlink(path)});


test("earned contribution can fund a new job without creating credits",async()=>{const s=await demo([doc,doc,doc,doc]);await transition(s,"demo","tick",{},start);await transition(s,"demo","tick",{},start+7000);await transition(s,"demo","tick",{},start+14000);const node=s.books.demo.nodes.find(n=>n.earned>=18);assert.ok(node);const before=Object.values(s.books.demo.accounts).reduce((a,b)=>a+b,0);await transition(s,"demo","create",request([doc],{payer:node.account}),start+15000);await transition(s,"demo","tick",{},start+15001);await transition(s,"demo","tick",{},start+22002);assert.equal(s.books.demo.jobs[0].payer,node.account);assert.equal(s.books.demo.jobs[0].spent,10);assert.equal(Object.values(s.books.demo.accounts).reduce((a,b)=>a+b,0),before);assertInvariants(s)});


